### ISSUE TITLE
Test in Lidar data

### ISSUE THREAD

**Issue by YmanChris** [Vegeta2020/SE-SSD#51]
Hi, I have a question about test function. If I want to test with my own unlabeled data, what should I do?

**Comment by TimGor1997** [comment]
> Hi, I have a question about test function. If I want to test with my own unlabeled data, what should I do?

Hi, I have the same question, have you found the solution?

**Comment by YmanChris** [comment]
> > Hi, I have a question about test function. If I want to test with my own unlabeled data, what should I do?
> 
> Hi, I have the same question, have you found the solution?

I modify the code of CIA-SSD , and solve it.

**Comment by TimGor1997** [comment]
I am very glad to receive your reply， could you share the code with me?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Vegeta2020/SE-SSD"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月26日(星期五) 中午12:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Vegeta2020/SE-SSD] Test in Lidar data (#51)





   
Hi, I have a question about test function. If I want to test with my own unlabeled data, what should I do?
  
Hi, I have the same question, have you found the solution?
  
I modify the code of CIA-SSD , and solve it.
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by YmanChris** [comment]
> I am very glad to receive your reply， could you share the code with me?
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Vegeta2020/SE-SSD" ***@***.***&gt;; 发送时间:&nbsp;2021年11月26日(星期五) 中午12:14 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [Vegeta2020/SE-SSD] Test in Lidar data (#51) Hi, I have a question about test function. If I want to test with my own unlabeled data, what should I do? Hi, I have the same question, have you found the solution? I modify the code of CIA-SSD , and solve it. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

Perhaps we have different envirment, we only use orig-points to infer without calib config. But I suggest you change code in package kitti and pipelines,
